package com.weathertraffic.model;

// Example structure generated by Chat GPT
public class WeatherStatus {
    private String description;
    private double temperature;
    private double windSpeed;

    // Getters
    public String getDescription() {
        return description;
    }

    public double getTemperature() {
        return temperature;
    }

    public double getWindSpeed() {
        return windSpeed;
    }

    //Setters
    public void setDescription(String newDescription) {
        this.description = newDescription;
    }

    public void setTemperature(double newTemperature) {
        this.temperature = newTemperature;
    }

    public void setWindSpeed(double newWindSpeed) {
        this.windSpeed = newWindSpeed;
    }
}
