package com.weathertraffic.model;

// Example structure generated by Chat GPT
public class WeatherStatus {
    private String description;
    private double cloudAmount;
    private double rainAmount;
    private double rainIntensity;
    private double temperature;
    private double snowAmount;
    private double visibility;
    private double windSpeed;

    // Getters
    public String getDescription() {
        return description;
    }

    public double getTemperature() {
        return temperature;
    }

    public double getWindSpeed() {
        return windSpeed;
    }

    public double getRainAmount() {
        return rainAmount;
    }

    public double getRainIntensity() {
        return rainIntensity;
    }

    public double getVisibility() {
        return visibility;
    }

    public double getCloudAmount() {
        return cloudAmount;
    }

    public double getSnowAmount() {
        return snowAmount;
    }

    //Setters
    public void setDescription(String newDescription) {
        this.description = newDescription;
    }

    public void setTemperature(double newTemperature) {
        this.temperature = newTemperature;
    }

    public void setWindSpeed(double newWindSpeed) {
        this.windSpeed = newWindSpeed;
    }

    public void setRainAmount(double rainAmount) {
        this.rainAmount = rainAmount;
    }

    public void setRainIntensity(double rainIntensity) {
        this.rainIntensity = rainIntensity;
    }

    public void setVisibility(double visibility) {
        this.visibility = visibility;
    }

    public void setCloudAmount(double cloudAmount) {
        this.cloudAmount = cloudAmount;
    }

    public void setSnowAmount(double snowAmount) {
        this.snowAmount = snowAmount;
    }
}
