package com.weathertraffic.model;

// Example structure generated by Chat GPT
public class WeatherStatus {
    private String description;
    private double temperature;
    private double windSpeed;
    private double rainAmount;
    private double rainIntensity;
    private double visibility;

    // Getters
    public String getDescription() {
        return description;
    }

    public double getTemperature() {
        return temperature;
    }

    public double getWindSpeed() {
        return windSpeed;
    }

    public double getRainAmount() {
        return rainAmount;
    }

    public double getRainIntensity() {
        return rainIntensity;
    }

    public double getVisibility() {
        return visibility;
    }

    //Setters
    public void setDescription(String newDescription) {
        this.description = newDescription;
    }

    public void setTemperature(double newTemperature) {
        this.temperature = newTemperature;
    }

    public void setWindSpeed(double newWindSpeed) {
        this.windSpeed = newWindSpeed;
    }

    public void setRainAmount(double rainAmount) {
        this.rainAmount = rainAmount;
    }

    public void setRainIntensity(double rainIntensity) {
        this.rainIntensity = rainIntensity;
    }

    public void setVisibility(double visibility) {
        this.visibility = visibility;
    }
}
